import os.path

SHARED_FOLDER_PATH = "//SOFTWARE/Software/"

UPDATE_WINDOWS_PS = "//SOFTWARE/Software/update_windows.ps1"

ON_SWITCH_PATH = SHARED_FOLDER_PATH + "res/on.png"
OFF_SWITCH_PATH = SHARED_FOLDER_PATH + "res/off.png"

WALLPAPER_SOURCE = SHARED_FOLDER_PATH + "PowerGPU.jpg"
WALLPAPER_COPY_DIR = os.path.expanduser("~/Pictures/PowerGPU.jpg")

SHOW_EULA_SYSPREP_PATH = SHARED_FOLDER_PATH + "showeula.xml"
SHOW_EULA_SYSPREP_COPY_DIR = "C:/Windows"

NVIDIA_VERSIONS_DIRECTORY = SHARED_FOLDER_PATH + "NVIDIA/"

SUPERPOSITION_SETUP_PATH = SHARED_FOLDER_PATH + "Unigine_Superposition-1.1.exe"
CREATE_SUPERPOSITION_UNINSTALLER = True

POWERPLAN_GUID = "8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c"

ARMOURY_CRATE_SETUP_PATH = SHARED_FOLDER_PATH + "ArmouryCrateInstaller.exe"
MSICENTER_SETUP_PATH = SHARED_FOLDER_PATH + "MSI Center_2.0.31.0.exe"

ICUE_SETUP_PATH = SHARED_FOLDER_PATH + "Install iCUE.exe"
SAMSUNG_MAGICIAN_SETUP_PATH = SHARED_FOLDER_PATH + "Samsung_Magician_Installer_Official_8.0.1.1000.exe"
LCONNECT_SETUP_PATH = SHARED_FOLDER_PATH + "L-Connect 3-x64-v2.0.10-d1c61000.exe"
NZXT_CAM_SETUP_PATH = SHARED_FOLDER_PATH + "NZXT-CAM-Setup.exe"
